/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lo.squisito.pizza;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Parth
 */
public class alt extends javax.swing.JFrame {
 

    /**
     * Creates new form alt
     */
    public alt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        staff_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        staff_pf = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        member_email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        member_pf = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(97, 212, 195));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("We deliver the finest");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lo Squ");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 39, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Staff Login");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 247, -1, -1));

        staff_id.setBackground(new java.awt.Color(97, 212, 195));
        staff_id.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        staff_id.setForeground(new java.awt.Color(255, 255, 255));
        staff_id.setText("enter your id");
        staff_id.setBorder(null);
        staff_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_idMouseClicked(evt);
            }
        });
        staff_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_idActionPerformed(evt);
            }
        });
        staff_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                staff_idFocusGained(evt);
            }
        });
        jPanel5.add(staff_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 357, 197, 29));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 316, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 387, 206, 7));

        staff_pf.setBackground(new java.awt.Color(97, 212, 195));
        staff_pf.setForeground(new java.awt.Color(255, 255, 255));
        staff_pf.setText("000000000000");
        staff_pf.setBorder(null);
        staff_pf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                staff_pfFocusGained(evt);
            }
        });
        jPanel5.add(staff_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 441, 197, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 461, 197, 10));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-pizza-50(2).png")); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Order");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 169, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 405, -1, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 482, 70, -1));

        jButton5.setBackground(new java.awt.Color(36, 47, 65));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Write us a feedback!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 630));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("isito Pizza");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-pizza-50(1).png")); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" pizzas to your doors!");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Now");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Members Login");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Facing Trouble? Contact us at help@losquisito.com");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        member_email.setBackground(new java.awt.Color(36, 47, 65));
        member_email.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        member_email.setForeground(new java.awt.Color(255, 255, 255));
        member_email.setText("enter your e-mail address");
        member_email.setBorder(null);
        member_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_emailMouseClicked(evt);
            }
        });
        member_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_emailActionPerformed(evt);
            }
        });
        member_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                member_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                member_emailFocusLost(evt);
            }
        });
        jPanel4.add(member_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 197, 29));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 220, 10));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        member_pf.setBackground(new java.awt.Color(36, 47, 65));
        member_pf.setForeground(new java.awt.Color(255, 255, 255));
        member_pf.setText("000000000000");
        member_pf.setBorder(null);
        member_pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_pfActionPerformed(evt);
            }
        });
        member_pf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                member_pfFocusGained(evt);
            }
        });
        jPanel4.add(member_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 197, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 220, 10));

        jButton2.setBackground(new java.awt.Color(97, 212, 195));
        jButton2.setText("Forgot Password?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, -1, 30));

        jButton3.setBackground(new java.awt.Color(97, 212, 195));
        jButton3.setForeground(new java.awt.Color(36, 47, 65));
        jButton3.setText("New?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 60, 30));

        jButton4.setBackground(new java.awt.Color(97, 212, 195));
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, 30));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("E-mail ID");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jButton6.setBackground(new java.awt.Color(97, 212, 195));
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void member_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_member_emailMouseClicked

    private void member_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_emailActionPerformed

    private void member_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_emailFocusGained
member_email.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_member_emailFocusGained

    private void staff_pfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_staff_pfFocusGained
        staff_pf.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_pfFocusGained

    private void staff_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_staff_idFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_staff_idFocusGained

    private void staff_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_idActionPerformed

    private void staff_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_idMouseClicked
        staff_id.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_idMouseClicked

    private void member_pfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_pfFocusGained
member_pf.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_member_pfFocusGained

    private void member_pfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_pfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_pfActionPerformed

    private void member_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_emailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_member_emailFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String pf=new String(staff_pf.getPassword());
if (pf.equals("admin")) {
admin a=new admin();
a.setVisible(true);
this.dispose();
}
else
    JOptionPane.showMessageDialog(null, "Incorrect combination");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String memberid=member_email.getText();
String pf2=new String(member_pf.getPassword());
String d="";
try {
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lo_squisito", "root", "tiger");
    Statement stmt=con.createStatement();
    String query="select ifnull((select cemail from customer where (cemail='"+memberid+"' && password='"+pf2+"')), '0') as output;";
    ResultSet rs=stmt.executeQuery(query);
    while (rs.next()) {
        d=rs.getString("output");
    }
    if (d.equals("0")) {
        JOptionPane.showMessageDialog(null, "Inccorect combination");
    }
    else {        
        mmenu a=new mmenu();
        a.setVisible(true);
        this.dispose();
    }
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null, "error");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String xyz=JOptionPane.showInputDialog("Please enter your registered e-mail address");
String dd="";
try {
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lo_squisito", "root", "tiger");
    Statement stmt=con.createStatement();
    String query="select ifnull((select cemail from customer where cemail='"+xyz+"'), '0') as output;";
    ResultSet rs=stmt.executeQuery(query);
    while (rs.next()) {
        dd=rs.getString("output");
    }
    if (dd.equals("0")) {
        JOptionPane.showMessageDialog(null, "You are not registered, click on 'New?' to make an account, takes less than 2 minutes! Or get help directly reaching us at hr@losquisito.com");
    }
    else
        JOptionPane.showMessageDialog(null, "Password successfully sent to your registered e-mail address");
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null, "error");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
signup a=new signup();
        a.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
feedback ob=new feedback();
ob.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField member_email;
    private javax.swing.JPasswordField member_pf;
    private javax.swing.JTextField staff_id;
    private javax.swing.JPasswordField staff_pf;
    // End of variables declaration//GEN-END:variables
}
