/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lo.squisito.pizza;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Parth
 */
public class mmenu extends javax.swing.JFrame {
    int k_m1=0, k_m2=0, k_m3=0;
    int k_c1=0, k_c2=0, k_c3=0;
    int k_r1=0, k_r2=0, k_r3=0;
    int k_s1=0, k_s2=0, k_s3=0;
    int k_p1=0, k_p2=0, k_p3=0;
    int k_f1=0, k_f2=0, k_f3=0;
    int k_t1=0, k_t2=0, k_t3=0;
    int k_q1=0, k_q2=0, k_q3=0;
    
    
    
    
    public String random_alphanumeric_generator(String d) {
        String s="ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"; //26+10=36
        String k="";
        for (int i=0; i<=7; i++) { 
            double z= Math.random()*36;
            int a=(int) z;
            char c=s.charAt(a);
            k=k+c;
        }
         d=k;
         return d;
    }
     
    
    public void textbox_veg_1() {
        if ((mb1.isSelected()==false) && (mb2.isSelected()==false) && (mb3.isSelected()==false)) {
            v1.setEnabled(false);
            v1.setText("");
        }
        else
            v1.setEnabled(true);
    }
    public void textbox_veg_2() {
        if ((cb1.isSelected()==false) && (cb2.isSelected()==false) && (cb3.isSelected()==false)) {
            v2.setEnabled(false);
            v2.setText("");
        }
        else
            v2.setEnabled(true);
    }
    public void textbox_veg_3() {
        if ((rb1.isSelected()==false) && (rb2.isSelected()==false) && (rb3.isSelected()==false)) {
            v3.setEnabled(false);
            v3.setText("");
        }
        else
            v3.setEnabled(true);
    }
    public void textbox_veg_4() {
        if ((sb1.isSelected()==false) && (sb2.isSelected()==false) && (sb3.isSelected()==false)) {
            v4.setEnabled(false);
            v4.setText("");
        }
        else
            v4.setEnabled(true);
    }
    public void textbox_nonveg_1() {
        if ((pb1.isSelected()==false) && (pb2.isSelected()==false) && (pb3.isSelected()==false)) {
            nv1.setEnabled(false);
            nv1.setText("");
        }
        else
            nv1.setEnabled(true);
    }
     public void textbox_nonveg_2() {
        if ((fb1.isSelected()==false) && (fb2.isSelected()==false) && (fb3.isSelected()==false)) {
            nv2.setEnabled(false);
            nv2.setText("");
        }
        else
            nv2.setEnabled(true);
    }
     public void textbox_nonveg_3() {
        if ((tb1.isSelected()==false) && (tb2.isSelected()==false) && (tb3.isSelected()==false)) {
            nv3.setEnabled(false);
            nv3.setText("");
        }
        else
            nv3.setEnabled(true);
    }
     public void textbox_nonveg_4() {
        if ((qb1.isSelected()==false) && (qb2.isSelected()==false) && (qb3.isSelected()==false)) {
            nv4.setEnabled(false);
            nv4.setText("");
        }
        else
            nv4.setEnabled(true);
    }
    
    /**
     * Creates new form mmenu
     */
    public mmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Margherita = new javax.swing.ButtonGroup();
        Corn = new javax.swing.ButtonGroup();
        Rughetta = new javax.swing.ButtonGroup();
        Sicily = new javax.swing.ButtonGroup();
        PeriPeri = new javax.swing.ButtonGroup();
        Fiesta = new javax.swing.ButtonGroup();
        Tuna = new javax.swing.ButtonGroup();
        Quadro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        mb1 = new javax.swing.JRadioButton();
        mb2 = new javax.swing.JRadioButton();
        mb3 = new javax.swing.JRadioButton();
        v4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cb3 = new javax.swing.JRadioButton();
        cb1 = new javax.swing.JRadioButton();
        cb2 = new javax.swing.JRadioButton();
        nv4 = new javax.swing.JTextField();
        rb3 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        v2 = new javax.swing.JTextField();
        sb3 = new javax.swing.JRadioButton();
        sb1 = new javax.swing.JRadioButton();
        sb2 = new javax.swing.JRadioButton();
        v3 = new javax.swing.JTextField();
        pb3 = new javax.swing.JRadioButton();
        pb1 = new javax.swing.JRadioButton();
        pb2 = new javax.swing.JRadioButton();
        v1 = new javax.swing.JTextField();
        fb3 = new javax.swing.JRadioButton();
        fb1 = new javax.swing.JRadioButton();
        fb2 = new javax.swing.JRadioButton();
        nv1 = new javax.swing.JTextField();
        tb3 = new javax.swing.JRadioButton();
        tb1 = new javax.swing.JRadioButton();
        tb2 = new javax.swing.JRadioButton();
        nv2 = new javax.swing.JTextField();
        qb3 = new javax.swing.JRadioButton();
        qb1 = new javax.swing.JRadioButton();
        qb2 = new javax.swing.JRadioButton();
        nv3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        redpasta = new javax.swing.JTextField();
        whitepasta = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        red = new javax.swing.JRadioButton();
        white = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        taxtax = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        grandtotal = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        offer = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        off = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setText("MENU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 130, 70));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-non-vegetarian-food-symbol-48.png")); // NOI18N
        jLabel2.setText("Non Veg Pizzas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 250, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Regular  Medium  Large  Qty.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 330, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Margherita");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("(Cheesy Classic)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Garlic Bread");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 140, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cheese & Corn");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 110, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 69, 0));
        jLabel9.setText("Italiano Rughetta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("(Arigula & Tomatoes)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 140, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-chef-hat-50.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-chef-hat-50.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 60));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 69, 0));
        jLabel13.setText("Sicily");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 220, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("(Green Olives & Herbs)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 150, 20));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-vegetarian-food-symbol-48.png")); // NOI18N
        jLabel15.setText("Veg Pizzas");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Regular  Medium  Large  Qty.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 330, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Chicken Peri Peri");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 190, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("(Peri-Peri Chicken with Red Paprika)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 220, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Chicken Fiesta");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 170, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("(Cheesy Classic)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 110, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 69, 0));
        jLabel21.setText("Italian Tuna");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 220, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("(Tuna in Olive Oil)");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 140, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 69, 0));
        jLabel23.setText("Quadro Formagi");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 220, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("(4 Types of Cheese and Chicken)");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 210, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-chef-hat-50.png")); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, 60));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\icons\\icons8-chef-hat-50.png")); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, 60));

        Margherita.add(mb1);
        mb1.setText("99");
        mb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb1ActionPerformed(evt);
            }
        });
        jPanel1.add(mb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        Margherita.add(mb2);
        mb2.setText("195");
        mb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb2ActionPerformed(evt);
            }
        });
        jPanel1.add(mb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        Margherita.add(mb3);
        mb3.setText("395");
        mb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb3ActionPerformed(evt);
            }
        });
        jPanel1.add(mb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        v4.setEnabled(false);
        jPanel1.add(v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 50, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("(INR)");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 40, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("(INR)");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 40, -1));

        Corn.add(cb3);
        cb3.setText("495");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        jPanel1.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        Corn.add(cb1);
        cb1.setText("165");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        Corn.add(cb2);
        cb2.setText("305");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        jPanel1.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        nv4.setEnabled(false);
        jPanel1.add(nv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 430, 50, -1));

        Rughetta.add(rb3);
        rb3.setText("595");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        jPanel1.add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        Rughetta.add(rb1);
        rb1.setText("205");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jPanel1.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        Rughetta.add(rb2);
        rb2.setText("385");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel1.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        v2.setEnabled(false);
        jPanel1.add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 50, -1));

        Sicily.add(sb3);
        sb3.setText("695");
        sb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb3ActionPerformed(evt);
            }
        });
        jPanel1.add(sb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        Sicily.add(sb1);
        sb1.setText("235");
        sb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb1ActionPerformed(evt);
            }
        });
        jPanel1.add(sb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        Sicily.add(sb2);
        sb2.setText("450");
        sb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sb2ActionPerformed(evt);
            }
        });
        jPanel1.add(sb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        v3.setEnabled(false);
        jPanel1.add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 50, -1));

        PeriPeri.add(pb3);
        pb3.setText("495");
        pb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb3ActionPerformed(evt);
            }
        });
        jPanel1.add(pb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 210, -1, -1));

        PeriPeri.add(pb1);
        pb1.setText("165");
        pb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb1ActionPerformed(evt);
            }
        });
        jPanel1.add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, -1, -1));

        PeriPeri.add(pb2);
        pb2.setText("305");
        pb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb2ActionPerformed(evt);
            }
        });
        jPanel1.add(pb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 210, -1, -1));

        v1.setEnabled(false);
        jPanel1.add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 50, -1));

        Fiesta.add(fb3);
        fb3.setText("595");
        fb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb3ActionPerformed(evt);
            }
        });
        jPanel1.add(fb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 270, -1, -1));

        Fiesta.add(fb1);
        fb1.setText("205");
        fb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb1ActionPerformed(evt);
            }
        });
        jPanel1.add(fb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, -1, -1));

        Fiesta.add(fb2);
        fb2.setText("385");
        fb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb2ActionPerformed(evt);
            }
        });
        jPanel1.add(fb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 270, -1, -1));

        nv1.setEnabled(false);
        jPanel1.add(nv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 210, 50, -1));

        Tuna.add(tb3);
        tb3.setText("695");
        tb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb3ActionPerformed(evt);
            }
        });
        jPanel1.add(tb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, -1, -1));

        Tuna.add(tb1);
        tb1.setText("235");
        tb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb1ActionPerformed(evt);
            }
        });
        jPanel1.add(tb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, -1, -1));

        Tuna.add(tb2);
        tb2.setText("450");
        tb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb2ActionPerformed(evt);
            }
        });
        jPanel1.add(tb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 350, -1, -1));

        nv2.setEnabled(false);
        jPanel1.add(nv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 270, 50, -1));

        Quadro.add(qb3);
        qb3.setText("835");
        qb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qb3ActionPerformed(evt);
            }
        });
        jPanel1.add(qb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 430, -1, -1));

        Quadro.add(qb1);
        qb1.setText("295");
        qb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qb1ActionPerformed(evt);
            }
        });
        jPanel1.add(qb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, -1, -1));

        Quadro.add(qb2);
        qb2.setText("555");
        qb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qb2ActionPerformed(evt);
            }
        });
        jPanel1.add(qb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 430, -1, -1));

        nv3.setEnabled(false);
        jPanel1.add(nv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 350, 50, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 630, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 502, 590, 10));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("Cheese & Corn");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 170, 40));
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 30, 30));

        jLabel31.setText("Rs. 95");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        jLabel32.setText("Qty.");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setText("Cheese Dip");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 140, 40));

        jLabel34.setText("Rs. 20");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 30, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setText("Pasta Italiano");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 160, 40));

        jLabel36.setText("Rs. 80");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, -1, -1));

        redpasta.setEnabled(false);
        jPanel1.add(redpasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 30, 30));

        whitepasta.setEnabled(false);
        jPanel1.add(whitepasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 30, 30));

        jLabel37.setText("Rs. 80");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, -1, -1));

        red.setText("Red Sauce");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        jPanel1.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, -1, -1));

        white.setText("White Sauce");
        white.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteActionPerformed(evt);
            }
        });
        jPanel1.add(white, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, -1, -1));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("Sides");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 100, 40));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel29.setText("Grand Total");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 650, 110, 30));

        total.setEditable(false);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 130, 30));

        taxtax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(taxtax, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 80, 20));

        gst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 50, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 220, 10));

        grandtotal.setEditable(false);
        jPanel1.add(grandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, 130, 40));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 0));
        jLabel40.setText("15% off on orders above Rs. 2000");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, -1, 40));

        offer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(offer, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 90, 20));

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel41.setText("Total");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 50, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Calculate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 610, -1, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 610, 110, 40));
        jPanel1.add(off, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, 100, 20));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 660, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\P.C. PAVAR\\Desktop\\IP Proj\\resized\\blurred\\2.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb1ActionPerformed
if (mb1.isSelected()==true) {
    k_m1++;
}
if (k_m1%2==0) {
    Margherita.clearSelection();
}
textbox_veg_1();  //to mamke textbox enabled/disabled
        // TODO add your handling code here:
    }//GEN-LAST:event_mb1ActionPerformed

    private void mb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb2ActionPerformed
if (mb2.isSelected()==true) {
    k_m2++;
}
if (k_m2%2==0) {
    Margherita.clearSelection();
}
textbox_veg_1();
        // TODO add your handling code here:
    }//GEN-LAST:event_mb2ActionPerformed

    private void mb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb3ActionPerformed
if (mb3.isSelected()==true) {
    k_m3++;
}
if (k_m3%2==0) {
    Margherita.clearSelection();
}
textbox_veg_1();
        // TODO add your handling code here:
    }//GEN-LAST:event_mb3ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
if (cb1.isSelected()==true) {
    k_c1++;
}
if (k_c1%2==0) {
    Corn.clearSelection();
}
textbox_veg_2();
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
if (cb2.isSelected()==true) {
    k_c2++;
}
if (k_c2%2==0) {
    Corn.clearSelection();
}
textbox_veg_2();
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
if (cb3.isSelected()==true) {
    k_c3++;
}
if (k_c3%2==0) {
    Corn.clearSelection();
}
textbox_veg_2();
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
if (rb1.isSelected()==true) {
    k_r1++;
}
if (k_r1%2==0) {
    Rughetta.clearSelection();
}
textbox_veg_3();
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
if (rb2.isSelected()==true) {
    k_r2++;
}
if (k_r2%2==0) {
    Rughetta.clearSelection();
}
textbox_veg_3();
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
if (rb3.isSelected()==true) {
    k_r3++;
}
if (k_r3%2==0) {
    Rughetta.clearSelection();
}
textbox_veg_3();
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void sb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb1ActionPerformed
if (sb1.isSelected()==true) {
    k_s1++;
}
if (k_s1%2==0) {
    Sicily.clearSelection();
}
textbox_veg_4();
        // TODO add your handling code here:
    }//GEN-LAST:event_sb1ActionPerformed

    private void sb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb2ActionPerformed
if (sb2.isSelected()==true) {
    k_s2++;
}
if (k_s2%2==0) {
    Sicily.clearSelection();
}
textbox_veg_4();
        // TODO add your handling code here:
    }//GEN-LAST:event_sb2ActionPerformed

    private void sb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sb3ActionPerformed
if (sb3.isSelected()==true) {
    k_s3++;
}
if (k_s3%2==0) {
    Sicily.clearSelection();
}
textbox_veg_4();
        // TODO add your handling code here:
    }//GEN-LAST:event_sb3ActionPerformed

    private void pb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb1ActionPerformed
if (pb1.isSelected()==true) {
    k_p1++;
}
if (k_p1%2==0) {
    PeriPeri.clearSelection();
}
textbox_nonveg_1();
        // TODO add your handling code here:
    }//GEN-LAST:event_pb1ActionPerformed

    private void pb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb2ActionPerformed
if (pb2.isSelected()==true) {
    k_p2++;
}
if (k_p2%2==0) {
    PeriPeri.clearSelection();
}
textbox_nonveg_1();
        // TODO add your handling code here:
    }//GEN-LAST:event_pb2ActionPerformed

    private void pb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb3ActionPerformed
if (pb3.isSelected()==true) {
    k_p3++;
}
if (k_p3%2==0) {
    PeriPeri.clearSelection();
}
textbox_nonveg_1();
        // TODO add your handling code here:
    }//GEN-LAST:event_pb3ActionPerformed

    private void fb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb1ActionPerformed
if (fb1.isSelected()==true) {
    k_f1++;
}
if (k_f1%2==0) {
    Fiesta.clearSelection();
}
textbox_nonveg_2();
        // TODO add your handling code here:
    }//GEN-LAST:event_fb1ActionPerformed

    private void fb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb2ActionPerformed
if (fb2.isSelected()==true) {
    k_f2++;
}
if (k_f2%2==0) {
    Fiesta.clearSelection();
}
textbox_nonveg_2();
        // TODO add your handling code here:
    }//GEN-LAST:event_fb2ActionPerformed

    private void fb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb3ActionPerformed
if (fb3.isSelected()==true) {
    k_f3++;
}
if (k_f3%2==0) {
    Fiesta.clearSelection();
}
textbox_nonveg_2();
        // TODO add your handling code here:
    }//GEN-LAST:event_fb3ActionPerformed

    private void tb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb1ActionPerformed
if (tb1.isSelected()==true) {
    k_t1++;
}
if (k_t1%2==0) {
    Tuna.clearSelection();
}
textbox_nonveg_3();
        // TODO add your handling code here:
    }//GEN-LAST:event_tb1ActionPerformed

    private void tb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb2ActionPerformed
if (tb2.isSelected()==true) {
    k_t2++;
}
if (k_t2%2==0) {
    Tuna.clearSelection();
}
textbox_nonveg_3();
        // TODO add your handling code here:
    }//GEN-LAST:event_tb2ActionPerformed

    private void tb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb3ActionPerformed
if (tb3.isSelected()==true) {
    k_t3++;
}
if (k_t3%2==0) {
    Tuna.clearSelection();
}
textbox_nonveg_3();
        // TODO add your handling code here:
    }//GEN-LAST:event_tb3ActionPerformed

    private void qb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qb1ActionPerformed
if (qb1.isSelected()==true) {
    k_q1++;
}
if (k_q1%2==0) {
    Quadro.clearSelection();
}
textbox_nonveg_4();
        // TODO add your handling code here:
    }//GEN-LAST:event_qb1ActionPerformed

    private void qb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qb2ActionPerformed
if (qb2.isSelected()==true) {
    k_q2++;
}
if (k_q2%2==0) {
    Quadro.clearSelection();
}
textbox_nonveg_4();
        // TODO add your handling code here:
    }//GEN-LAST:event_qb2ActionPerformed

    private void qb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qb3ActionPerformed
if (qb3.isSelected()==true) {
    k_q3++;
}
if (k_q3%2==0) {
    Quadro.clearSelection();
}
textbox_nonveg_4();
        // TODO add your handling code here:
    }//GEN-LAST:event_qb3ActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
if (red.isSelected()==true) {
    redpasta.setEnabled(true);
}
else {
    redpasta.setEnabled(false);
    redpasta.setText("");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_redActionPerformed

    private void whiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteActionPerformed
if (white.isSelected()==true) {
    whitepasta.setEnabled(true);
}
else {
    whitepasta.setEnabled(false);
    whitepasta.setText("");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_whiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
total.setText("");
try {        // try catch because for example rv1= (Integer.parseInt(v1.getText())) * (Integer.parseInt(mb1.getText())); works only when v1 has qty specified
int rv1=0, rv2=0, rv3=0, rv4=0, rnv1=0, rnv2=0, rnv3=0, rnv4=0;
if (mb1.isSelected()==true)
    rv1= (Integer.parseInt(v1.getText())) * (Integer.parseInt(mb1.getText()));  //else if not neccesary because if not "if", rv1=0 predefined
if (mb2.isSelected()==true)
    rv1= (Integer.parseInt(v1.getText())) * (Integer.parseInt(mb2.getText()));
if (mb3.isSelected()==true)
    rv1= (Integer.parseInt(v1.getText())) * (Integer.parseInt(mb3.getText()));
if (cb1.isSelected()==true)
    rv2= (Integer.parseInt(v2.getText())) * (Integer.parseInt(cb1.getText()));
if (cb2.isSelected()==true)
    rv2= (Integer.parseInt(v2.getText())) * (Integer.parseInt(cb2.getText()));
if (cb3.isSelected()==true)
    rv2= (Integer.parseInt(v2.getText())) * (Integer.parseInt(cb3.getText()));
if (rb1.isSelected()==true)
    rv3= (Integer.parseInt(v3.getText())) * (Integer.parseInt(rb1.getText()));
if (rb2.isSelected()==true)
    rv3= (Integer.parseInt(v3.getText())) * (Integer.parseInt(rb2.getText()));
if (rb3.isSelected()==true)
    rv3= (Integer.parseInt(v3.getText())) * (Integer.parseInt(rb3.getText()));
if (sb1.isSelected()==true)
    rv4= (Integer.parseInt(v4.getText())) * (Integer.parseInt(sb1.getText()));
if (sb2.isSelected()==true)
    rv4= (Integer.parseInt(v4.getText())) * (Integer.parseInt(sb2.getText()));
if (sb3.isSelected()==true)
    rv4= (Integer.parseInt(v4.getText())) * (Integer.parseInt(sb3.getText()));
if (pb1.isSelected()==true)
    rnv1= (Integer.parseInt(nv1.getText())) * (Integer.parseInt(pb1.getText()));
if (pb2.isSelected()==true)
    rnv1= (Integer.parseInt(nv1.getText())) * (Integer.parseInt(pb2.getText()));
if (pb3.isSelected()==true)
    rnv1= (Integer.parseInt(nv1.getText())) * (Integer.parseInt(pb3.getText()));
if (fb1.isSelected()==true)
    rnv2= (Integer.parseInt(nv2.getText())) * (Integer.parseInt(fb1.getText()));
if (fb2.isSelected()==true)
    rnv2= (Integer.parseInt(nv2.getText())) * (Integer.parseInt(fb2.getText()));
if (fb3.isSelected()==true)
    rnv2= (Integer.parseInt(nv2.getText())) * (Integer.parseInt(fb3.getText()));
if (tb1.isSelected()==true)
    rnv3= (Integer.parseInt(nv3.getText())) * (Integer.parseInt(rb1.getText()));
if (tb2.isSelected()==true)
    rnv3= (Integer.parseInt(nv3.getText())) * (Integer.parseInt(rb2.getText()));
if (tb3.isSelected()==true)
    rnv3= (Integer.parseInt(nv3.getText())) * (Integer.parseInt(rb3.getText()));
if (qb1.isSelected()==true)
    rnv4= (Integer.parseInt(nv4.getText())) * (Integer.parseInt(qb1.getText()));
if (qb2.isSelected()==true)
    rnv4= (Integer.parseInt(nv4.getText())) * (Integer.parseInt(qb2.getText()));
if (qb3.isSelected()==true)
    rnv4= (Integer.parseInt(nv4.getText())) * (Integer.parseInt(qb3.getText()));

int p1=0, p2=0;
if (white.isSelected()==true)
    p1=80*Integer.parseInt(whitepasta.getText());
if (red.isSelected()==true)
    p2=80*Integer.parseInt(redpasta.getText());

int rs1=0, rs2=0;
if (s1.getText().equals("")) {}
else rs1=Integer.parseInt(s1.getText())*95;
if (s2.getText().equals("")) {}
else rs2=Integer.parseInt(s2.getText())*20;

int t=rv1+rv2+rv3+rv4+rnv1+rnv2+rnv3+rnv4+rs1+rs2+p1+p2;
total.setText(t+"");
double tax=  t*0.05;
gst.setText(tax+"");
taxtax.setText("+5% GST");
double offf=t*0.15;
if (t>=2000) {
       offer.setText("-15% Offer!");
       off.setText(offf+"");
       grandtotal.setText(t+tax-offf+"");
    }
else {
   grandtotal.setText(t+tax+""); 
 }
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Please specify quantity of the selected items or check your entries");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
boolean r=true;
try {
    double x1=Double.parseDouble(grandtotal.getText());
}
catch (Exception e) {
    r=false;
}
if (r==true) {
    int z=JOptionPane.showConfirmDialog(null, "Your bill is "+grandtotal.getText()+". Confirm order?");
    if (z==0) {
        String x="";
        String orderno=random_alphanumeric_generator(x);
        System.out.println(orderno);
        try {
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lo_squisito", "root", "tiger");
           Statement stmt=con.createStatement();
           String query="insert into orderdetails (ono, bill, odate) values ('"+orderno+"', "+grandtotal.getText()+", now());";
           int rs=stmt.executeUpdate(query);
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error in connectivity");
        }
        
        
        payment a=new payment();
        a.setVisible(true);
        this.dispose();
}}
else
    JOptionPane.showMessageDialog(null, "Select atleast one item");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int co=JOptionPane.showConfirmDialog(null, "Are you sure you want to go back to main menu?");
if (co==0) {
    alt ob=new alt();
    ob.setVisible(true);
    this.dispose();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**s
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Corn;
    private javax.swing.ButtonGroup Fiesta;
    private javax.swing.ButtonGroup Margherita;
    private javax.swing.ButtonGroup PeriPeri;
    private javax.swing.ButtonGroup Quadro;
    private javax.swing.ButtonGroup Rughetta;
    private javax.swing.ButtonGroup Sicily;
    private javax.swing.ButtonGroup Tuna;
    private javax.swing.JRadioButton cb1;
    private javax.swing.JRadioButton cb2;
    private javax.swing.JRadioButton cb3;
    private javax.swing.JRadioButton fb1;
    private javax.swing.JRadioButton fb2;
    private javax.swing.JRadioButton fb3;
    private javax.swing.JTextField grandtotal;
    private javax.swing.JLabel gst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton mb1;
    private javax.swing.JRadioButton mb2;
    private javax.swing.JRadioButton mb3;
    private javax.swing.JTextField nv1;
    private javax.swing.JTextField nv2;
    private javax.swing.JTextField nv3;
    private javax.swing.JTextField nv4;
    private javax.swing.JLabel off;
    private javax.swing.JLabel offer;
    private javax.swing.JRadioButton pb1;
    private javax.swing.JRadioButton pb2;
    private javax.swing.JRadioButton pb3;
    private javax.swing.JRadioButton qb1;
    private javax.swing.JRadioButton qb2;
    private javax.swing.JRadioButton qb3;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton red;
    private javax.swing.JTextField redpasta;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JRadioButton sb1;
    private javax.swing.JRadioButton sb2;
    private javax.swing.JRadioButton sb3;
    private javax.swing.JLabel taxtax;
    private javax.swing.JRadioButton tb1;
    private javax.swing.JRadioButton tb2;
    private javax.swing.JRadioButton tb3;
    private javax.swing.JTextField total;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JRadioButton white;
    private javax.swing.JTextField whitepasta;
    // End of variables declaration//GEN-END:variables
}
