/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lo.squisito.pizza;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Parth
 */
public class order extends javax.swing.JFrame {

    /**
     * Creates new form order
     */
    public order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        in = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        r1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        r2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        r3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        otable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 34, 98));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(76, 41, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Search Order Number");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 10));

        in.setBackground(new java.awt.Color(39, 34, 98));
        in.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        in.setForeground(new java.awt.Color(255, 255, 255));
        in.setBorder(null);
        jPanel1.add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 123, 33));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        r1.setEditable(false);
        r1.setBackground(new java.awt.Color(39, 34, 98));
        r1.setForeground(new java.awt.Color(204, 204, 204));
        r1.setBorder(null);
        jPanel1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, 30));

        ta.setEditable(false);
        ta.setBackground(new java.awt.Color(39, 34, 98));
        ta.setColumns(20);
        ta.setForeground(new java.awt.Color(255, 255, 255));
        ta.setLineWrap(true);
        ta.setRows(5);
        ta.setBorder(null);
        jScrollPane2.setViewportView(ta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 140, 80));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 190, 10));

        r2.setEditable(false);
        r2.setBackground(new java.awt.Color(39, 34, 98));
        r2.setForeground(new java.awt.Color(204, 204, 204));
        r2.setBorder(null);
        jPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 10));

        r3.setEditable(false);
        r3.setBackground(new java.awt.Color(39, 34, 98));
        r3.setForeground(new java.awt.Color(204, 204, 204));
        r3.setBorder(null);
        jPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, 10));

        jButton2.setText("Retrieve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        otable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Date & Time", "Bill", "Feedback"
            }
        ));
        otable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(otable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otableMouseClicked
ta.setText("");
DefaultTableModel model = (DefaultTableModel) otable.getModel();
int a=otable.getSelectedRow();
String is=(String) model.getValueAt(a, 0);
try {
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lo_squisito", "root", "tiger");
    Statement stmt=con.createStatement();
    String query="Select * from orderdetails where ono='"+is+"';"; // single quotes save the day!
    ResultSet rs=stmt.executeQuery(query);
    while (rs.next()) {
        String no=rs.getString("ono");
        String datetime=rs.getString("odate");
        String amt=rs.getString("bill");
        String fb=rs.getString("feedback");
        r1.setText(no);
        r2.setText(datetime);
        r3.setText(amt);
        ta.append(fb);
    }
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null, "error");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_otableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model = (DefaultTableModel) otable.getModel();
model.setRowCount(0);
try {
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lo_squisito", "root", "tiger");
    Statement stmt=con.createStatement();
    String query="Select * from orderdetails;";
    ResultSet rs=stmt.executeQuery(query);
    while (rs.next()) {
        String no=rs.getString("ono");
        String datetime=rs.getString("odate");
        String amt=rs.getString("bill");
        String fb=rs.getString("feedback");
        model.addRow(new Object[] {no, datetime, amt, fb});
    }
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel model = (DefaultTableModel) otable.getModel();
model.setRowCount(0);
try {
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/lo_squisito", "root", "tiger");
    Statement stmt=con.createStatement();
    String query="Select * from orderdetails where ono='"+in.getText()+"';";
    ResultSet rs=stmt.executeQuery(query);
    while (rs.next()) {
        String no=rs.getString("ono");
        String datetime=rs.getString("odate");
        String amt=rs.getString("bill");
        String fb=rs.getString("feedback");
        model.addRow(new Object[] {no, datetime, amt, fb});
    }
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Invalid Order Number");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
admin obb=new admin();
obb.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable otable;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
